# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - IOT-API-DEVELOPMENT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ff744e26f14f41a492f2592d6bd9fa89 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d48bd6cabb2a495d962e3918fb8cd3a9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ff744e26f14f41a492f2592d6bd9fa89 }}/tanaxer/asdf:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'IOT-API-DEVELOPMENT'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b80e2c1dd73b4832ad3ec0f18029869b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ff744e26f14f41a492f2592d6bd9fa89 }}/tanaxer/asdf:${{ github.sha }}'